AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  BaseRegion:
    Fn::Equals:
      - eu-west-1
      - Ref: AWS::Region
  ClusterStackOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: ClusterStack
          - ''
  ContainerDefinitions1Command:
    Fn::Or:
      - Condition: ContainerDefinitions1CommandOverride
      - Fn::Equals:
          - 'True'
          - 'True'
  ContainerDefinitions1CommandOverride:
    Fn::Not:
      - Fn::Equals:
          - Fn::Select:
              - 0
              - Ref: ContainerDefinitions1Command
          - ''
  ContainerDefinitions1ContainerPort:
    Fn::Not:
      - Fn::Equals:
          - 0
          - 0
  ContainerDefinitions1CpuOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: ContainerDefinitions1Cpu
          - ''
  ContainerDefinitions1HostPort:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  ContainerDefinitions1MemoryOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: ContainerDefinitions1Memory
          - ''
  ContainerDefinitions1MemoryReservationOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: ContainerDefinitions1MemoryReservation
          - ''
  CpuOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: Cpu
          - ''
  CpuTask:
    Fn::Or:
      - Fn::And:
          - Condition: CpuOverride
          - Fn::Not:
              - Fn::Equals:
                  - Ref: Cpu
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: CpuOverride
          - Fn::Not:
              - Fn::Equals:
                  - None
                  - None
  DockerLabelLastUpdateOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: DockerLabelLastUpdate
          - ''
  LaunchTypeFarGate:
    Fn::Or:
      - Fn::And:
          - Condition: LaunchTypeOverride
          - Fn::Equals:
              - Ref: LaunchType
              - FARGATE
      - Fn::And:
          - Fn::Not:
              - Condition: LaunchTypeOverride
          - Fn::Equals:
              - EC2
              - FARGATE
  LaunchTypeOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: LaunchType
          - ''
  LoadBalancerApplicationStackOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: LoadBalancerApplicationStack
          - ''
  LogConfiguration:
    Fn::Or:
      - Fn::And:
          - Condition: LogDriverOverride
          - Fn::Not:
              - Fn::Equals:
                  - Ref: LogDriver
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: LogDriverOverride
          - Fn::Not:
              - Fn::Equals:
                  - awslogs
                  - None
  LogDriverOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: LogDriver
          - ''
  MemoryOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: Memory
          - ''
  NetworkModeAwsVpc:
    Fn::Or:
      - Fn::And:
          - Condition: NetworkModeOverride
          - Fn::Equals:
              - Ref: NetworkMode
              - awsvpc
      - Fn::And:
          - Fn::Not:
              - Condition: NetworkModeOverride
          - Fn::Equals:
              - bridge
              - awsvpc
      - Condition: LaunchTypeFarGate
  NetworkModeOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: NetworkMode
          - ''
  NetworkModeStandard:
    Fn::Or:
      - Fn::And:
          - Condition: NetworkModeOverride
          - Fn::Not:
              - Fn::Equals:
                  - Ref: NetworkMode
                  - awsvpc
      - Fn::And:
          - Fn::Not:
              - Condition: NetworkModeOverride
          - Fn::Not:
              - Fn::Equals:
                  - bridge
                  - awsvpc
Description: reserve-cpu (Generated by awsibox 0.2.20) [ecs]
Mappings:
  dev:
    eu-central-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
    eu-west-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
    us-east-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
  prd:
    eu-central-1:
      ContainerDefinitions1Cpu: 256
      ScheduledActionUpCapacityMax: k
      ScheduledActionUpCapacityMin: k
    eu-west-1:
      ContainerDefinitions1Cpu: 256
      ScheduledActionUpCapacityMax: k
      ScheduledActionUpCapacityMin: k
    us-east-1:
      ContainerDefinitions1Cpu: 256
      ScheduledActionUpCapacityMax: k
      ScheduledActionUpCapacityMin: k
  stg:
    eu-central-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
    eu-west-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
    us-east-1:
      AlarmTargetExternal5XXEvaluationPeriods: 0
      AlarmTargetInternal5XXEvaluationPeriods: 0
      ContainerDefinitions1Cpu: 512
      ScheduledActionUpCapacityMax: CapacityMax
      ScheduledActionUpCapacityMin: CapacityMin
Outputs:
  BrandDomain:
    Value: numenor.arda
  ContainerDefinitions1Command:
    Condition: ContainerDefinitions1Command
    Value:
      Fn::Join:
        - ','
        - Fn::If:
            - ContainerDefinitions1CommandOverride
            - Ref: ContainerDefinitions1Command
            - - tail
              - -f
              - .dockerenv
  ContainerDefinitions1Constraints:
    Value:
      Fn::Join:
        - ''
        - - Cpu=
          - Fn::If:
              - CpuTask
              - Fn::If:
                  - CpuOverride
                  - Ref: Cpu
                  - None
              - Fn::If:
                  - ContainerDefinitions1CpuOverride
                  - Ref: ContainerDefinitions1Cpu
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - ContainerDefinitions1Cpu
          - ',Memory='
          - Fn::If:
              - LaunchTypeFarGate
              - Fn::If:
                  - MemoryOverride
                  - Ref: Memory
                  - 512
              - Fn::If:
                  - ContainerDefinitions1MemoryOverride
                  - Ref: ContainerDefinitions1Memory
                  - 64
          - ',MemoryReservation='
          - Fn::If:
              - ContainerDefinitions1MemoryReservationOverride
              - Ref: ContainerDefinitions1MemoryReservation
              - 32
  ContainerDefinitions1Environment:
    Value:
      Fn::Sub: ''
  Cpu:
    Condition: CpuTask
    Value:
      Fn::If:
        - CpuOverride
        - Ref: Cpu
        - None
  Env:
    Value:
      Ref: Env
  EnvApp1Version:
    Value:
      Ref: EnvApp1Version
  EnvRole:
    Value:
      Ref: EnvRole
  EnvStackVersion:
    Value:
      Ref: EnvStackVersion
  LaunchType:
    Value:
      Fn::If:
        - LaunchTypeOverride
        - Ref: LaunchType
        - EC2
  LogDriver:
    Value:
      Fn::If:
        - LogDriverOverride
        - Ref: LogDriver
        - awslogs
  Memory:
    Condition: LaunchTypeFarGate
    Value:
      Fn::If:
        - MemoryOverride
        - Ref: Memory
        - 512
  NetworkMode:
    Value:
      Fn::If:
        - NetworkModeAwsVpc
        - awsvpc
        - Fn::If:
            - NetworkModeOverride
            - Ref: NetworkMode
            - bridge
  StackType:
    Value: ecs
Parameters:
  ClusterStack:
    Default: ''
    Description: Cluster Stack Name used to launch service on - empty for default
      based on env/role
    Type: String
  ContainerDefinitions1Command:
    Default: ''
    Description: Command to execute
    Type: CommaDelimitedList
  ContainerDefinitions1Cpu:
    Default: ''
    Description: Cpu Share - empty for mapped value
    Type: String
  ContainerDefinitions1Memory:
    Default: ''
    Description: Memory hard limit - empty for mapped value
    Type: String
  ContainerDefinitions1MemoryReservation:
    Default: ''
    Description: Memory soft limit - empty for mapped value
    Type: String
  Cpu:
    AllowedValues:
      - ''
      - None
      - '128'
      - '256'
      - '384'
      - '512'
      - '640'
      - '768'
      - '896'
      - '1024'
      - '1152'
      - '1280'
      - '1408'
      - '1536'
      - '1664'
      - '1792'
      - '1920'
      - '2048'
      - '2176'
      - '2304'
      - '2432'
      - '2560'
      - '2688'
      - '2816'
      - '2944'
      - '3072'
      - '3200'
      - '3328'
      - '3456'
      - '3584'
      - '3712'
      - '3840'
      - '3968'
      - '4096'
    Default: ''
    Description: Cpu used by task - empty for default based on env/role
    Type: String
  DockerLabelLastUpdate:
    Default: ''
    Description: 'Use to force redeploy - can use: $(date +%F_%T)'
    Type: String
  Env:
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
    Description: Environment
    Type: String
  EnvApp1Version:
    AllowedPattern: ^[a-zA-Z0-9-_.]*$
    Default: '1'
    Description: EnvApp1Version
    Type: String
  EnvRole:
    AllowedPattern: ^[a-zA-Z0-9-_.]*$
    Default: ''
    Description: Service Role
    Type: String
  EnvShort:
    AllowedValues:
      - dev
      - stg
      - prd
    Default: dev
    Description: Environment Short - NEVER CHANGE!
    Type: String
  EnvStackVersion:
    Default: '1'
    Description: Stack version, if changed with UpdateMode=Cfn triggers cfn-hup
    Type: String
  LaunchType:
    AllowedValues:
      - ''
      - EC2
      - FARGATE
    Default: ''
    Description: RunTask LaunchType - empty for default based on env/role
    Type: String
  LoadBalancerApplicationStack:
    Default: ''
    Description: LoadBalancer Application Stack to use - empty for default based on
      env/role
    Type: String
  LogDriver:
    AllowedValues:
      - ''
      - None
      - awslogs
      - fluentd
      - gelf
      - journald
      - json-file
      - splunk
      - syslog
    Default: ''
    Description: Log driver for task container - empty for default
    Type: String
  Memory:
    Default: ''
    Description: Memory used by task - empty for default based on env/role
    Type: String
  NetworkMode:
    AllowedValues:
      - ''
      - awsvpc
      - bridge
    Default: ''
    Description: Task NetworkMode - empty for default based on env/role
    Type: String
Resources:
  IAMPolicyParameterStore:
    Properties:
      PolicyDocument:
        Statement:
          - Action: kms:Decrypt
            Effect: Allow
            Resource:
              Fn::ImportValue: KeyParameterStore
          - Action: ssm:DescribeParameters
            Effect: Allow
            Resource:
              Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:*
          - Action: ssm:GetParameters
            Effect: Allow
            Resource:
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${EnvRole}/*
              - Fn::Sub: arn:aws:ssm:${AWS::Region}:${AWS::AccountId}:parameter/${AWS::StackName}/${EnvRole}/*
        Version: '2012-10-17'
      PolicyName: ParameterStore
      Roles:
        - Ref: RoleTask
    Type: AWS::IAM::Policy
  LogsLogGroup:
    Properties:
      LogGroupName:
        Fn::Sub: /aws/ecs/${AWS::StackName}
      RetentionInDays: 30
    Type: AWS::Logs::LogGroup
  RoleTask:
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - Fn::ImportValue: IAMPolicyCloudWatchPutMetric
      Path: /
    Type: AWS::IAM::Role
  SecurityGroupEcsService:
    Condition: NetworkModeAwsVpc
    Properties:
      GroupDescription: Enable access to Service
      SecurityGroupIngress: []
      VpcId:
        Fn::ImportValue: VpcId
    Type: AWS::EC2::SecurityGroup
  Service:
    Properties:
      Cluster:
        Fn::ImportValue:
          Fn::Sub:
            - Cluster-${ClusterStack}
            - ClusterStack:
                Fn::If:
                  - ClusterStackOverride
                  - Ref: ClusterStack
                  - ecs-a
      HealthCheckGracePeriodSeconds:
        Ref: AWS::NoValue
      NetworkConfiguration:
        Fn::If:
          - NetworkModeAwsVpc
          - AwsvpcConfiguration:
              SecurityGroups:
                - Fn::GetAtt:
                    - SecurityGroupEcsService
                    - GroupId
              Subnets:
                Fn::Split:
                  - ','
                  - Fn::ImportValue: SubnetsPrivate
          - Ref: AWS::NoValue
      PlatformVersion:
        Fn::If:
          - LaunchTypeFarGate
          - LATEST
          - Ref: AWS::NoValue
      SchedulingStrategy: DAEMON
      TaskDefinition:
        Ref: TaskDefinition
    Type: AWS::ECS::Service
  TaskDefinition:
    Properties:
      ContainerDefinitions:
        - Command:
            Fn::If:
              - ContainerDefinitions1CommandOverride
              - Ref: ContainerDefinitions1Command
              - - tail
                - -f
                - .dockerenv
          Cpu:
            Fn::If:
              - CpuTask
              - Fn::If:
                  - CpuOverride
                  - Ref: Cpu
                  - None
              - Fn::If:
                  - ContainerDefinitions1CpuOverride
                  - Ref: ContainerDefinitions1Cpu
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - ContainerDefinitions1Cpu
          DockerLabels:
            LastUpdate:
              Ref: DockerLabelLastUpdate
          Environment:
            - Name: Env
              Value:
                Ref: Env
            - Name: EnvAbbr
              Value:
                Ref: EnvShort
            - Name: EnvRole
              Value:
                Ref: EnvRole
            - Name: EnvStackName
              Value:
                Ref: AWS::StackName
            - Name: EnvRegion
              Value:
                Ref: AWS::Region
            - Name: EnvBrand
              Value: numenor.arda
            - Name: EnvClusterStackName
              Value:
                Fn::If:
                  - ClusterStackOverride
                  - Ref: ClusterStack
                  - ecs-a
            - Name: NODE_ENV
              Value: production
          Essential: 'true'
          Image: amazonlinux:2
          LogConfiguration:
            Fn::If:
              - LogConfiguration
              - LogDriver:
                  Fn::If:
                    - LogDriverOverride
                    - Ref: LogDriver
                    - awslogs
                Options:
                  awslogs-group:
                    Ref: LogsLogGroup
                  awslogs-region:
                    Ref: AWS::Region
                  awslogs-stream-prefix:
                    Ref: AWS::StackName
              - Ref: AWS::NoValue
          Memory:
            Fn::If:
              - LaunchTypeFarGate
              - Fn::If:
                  - MemoryOverride
                  - Ref: Memory
                  - 512
              - Fn::If:
                  - ContainerDefinitions1MemoryOverride
                  - Ref: ContainerDefinitions1Memory
                  - 64
          MemoryReservation:
            Fn::If:
              - ContainerDefinitions1MemoryReservationOverride
              - Ref: ContainerDefinitions1MemoryReservation
              - 32
          Name:
            Ref: EnvRole
          PortMappings:
            Fn::If:
              - ContainerDefinitions1ContainerPort
              - - ContainerPort: 0
                  HostPort:
                    Fn::If:
                      - NetworkModeAwsVpc
                      - 0
                      - Fn::If:
                          - ContainerDefinitions1HostPort
                          - None
                          - 0
                  Protocol: tcp
              - Ref: AWS::NoValue
      Cpu:
        Fn::If:
          - CpuTask
          - Fn::If:
              - CpuOverride
              - Ref: Cpu
              - None
          - Ref: AWS::NoValue
      ExecutionRoleArn:
        Fn::If:
          - LaunchTypeFarGate
          - Fn::ImportValue: RoleECSTaskExecution
          - Ref: AWS::NoValue
      Memory:
        Fn::If:
          - LaunchTypeFarGate
          - Fn::If:
              - MemoryOverride
              - Ref: Memory
              - 512
          - Ref: AWS::NoValue
      NetworkMode:
        Fn::If:
          - NetworkModeAwsVpc
          - awsvpc
          - Fn::If:
              - NetworkModeOverride
              - Ref: NetworkMode
              - bridge
      RequiresCompatibilities:
        Fn::If:
          - LaunchTypeFarGate
          - - EC2
            - FARGATE
          - - EC2
      TaskRoleArn:
        Ref: RoleTask
    Type: AWS::ECS::TaskDefinition

