global:
  EC2SecurityGroupIngress:
    - EFS:
        IBOX_ENABLED: False
        FromPort: 2049
        GroupId: GetAtt(f"SecurityGroup{IBOX_LINKED_OBJ_NAME}Server", "GroupId")
        SourceSecurityGroupId: Ref(f"SecurityGroup{IBOX_LINKED_OBJ_NAME}Client")
        ToPort: 2049
    - EC2LoadBalancerClassicInstancesRule:
        IBOX_ENABLED: False
        FromPort: get_endvalue(f"{IBOX_LINKED_OBJ_NAME}Listeners{IBOX_LINKED_OBJ_INDEX}InstancePort")
        GroupId: GetAtt("SecurityGroupInstancesRules", "GroupId")
        SourceSecurityGroupId: Ref("SecurityGroupLoadBalancer")
        ToPort: get_endvalue(f"{IBOX_LINKED_OBJ_NAME}Listeners{IBOX_LINKED_OBJ_INDEX}InstancePort")
    - EC2LoadBalancerApplicationInstancesRule:
        IBOX_ENABLED: False
        FromPort: get_endvalue(f"ElasticLoadBalancingV2TargetGroup{IBOX_LINKED_OBJ_NAME}Port")
        GroupId: GetAtt("SecurityGroupInstancesRules", "GroupId")
        SourceSecurityGroupId: Ref("SecurityGroupLoadBalancer")
        ToPort: get_endvalue(f"ElasticLoadBalancingV2TargetGroup{IBOX_LINKED_OBJ_NAME}Port")
    - EC2LoadBalancerNetworkInstancesRule:
        IBOX_ENABLED: False
        CidrIp: ImportValue("VPCCidr")
        FromPort: get_endvalue(f"ElasticLoadBalancingV2TargetGroup{IBOX_LINKED_OBJ_NAME}Port")
        GroupId: GetAtt("SecurityGroupInstancesRules", "GroupId")
        ToPort: get_endvalue(f"ElasticLoadBalancingV2TargetGroup{IBOX_LINKED_OBJ_NAME}Port")
    - ECSLoadBalancerApplicationLoadBalancerRule:
        IBOX_ENABLED: False
        CidrIp: '0.0.0.0/0'
        FromPort: get_endvalue(f'{IBOX_LINKED_OBJ_NAME}Port')
        GroupId: get_expvalue(f'SecurityGroupLoadBalancerApplication{IBOX_LINKED_OBJ_INDEX}', 'LoadBalancerApplicationStack')
        ToPort: get_endvalue(f'{IBOX_LINKED_OBJ_NAME}Port')
