global:
  EC2SecurityGroupIngress:
    - EFS:
        IBOX_ENABLED: False
        FromPort: 2049
        GroupId: GetAtt(f"SecurityGroup{IBOX_LINKED_OBJ_NAME}Server", "GroupId")
        SourceSecurityGroupId: Ref(f"SecurityGroup{IBOX_LINKED_OBJ_NAME}Client")
        ToPort: 2049
    - ELBListener:
        IBOX_ENABLED: False
        FromPort: get_endvalue(f"{IBOX_LINKED_OBJ_NAME}Listeners{IBOX_LINKED_OBJ_INDEX}InstancePort")
        GroupId: GetAtt("SecurityGroupInstancesRules", "GroupId")
        SourceSecurityGroupId: Ref("SecurityGroupLoadBalancer")
        ToPort: get_endvalue(f"{IBOX_LINKED_OBJ_NAME}Listeners{IBOX_LINKED_OBJ_INDEX}InstancePort")
