Base: &base
  IBOXENABLED: False
  ScalingTargetId: Ref('ScalableTarget')
  PolicyName: IBOXRESNAME

Tracking: &tracking
  <<: *base
  Condition: IBOXRESNAME
  IBOXPARAMETER:
    - IBOXRESNAMETargetTrackingScalingPolicyConfigurationCustomizedMetricSpecificationStatistic:
        Description: '0 to disable - empty for mapped value'
    - IBOXRESNAMETargetTrackingScalingPolicyConfigurationTargetValue:
        Description: '0 to disable - empty for mapped value'
  IBOXCONDITION:
    - IBOXRESNAME:
        get_condition('', 'not_equals', '0', f'{IBOXRESNAME}TargetTrackingScalingPolicyConfigurationTargetValue')
  PolicyType: TargetTrackingScaling

Step: &step
  <<: *base
  PolicyType: StepScaling
  StepScalingPolicyConfiguration:
    AdjustmentType: ChangeInCapacity
    MetricAggregationType: Average

TrackingCpu: &trackingcpu
  <<: *tracking
  Type: Cpu
  TargetTrackingScalingPolicyConfiguration:
    PredefinedMetricSpecification:
      PredefinedMetricType: 'ECSServiceAverageCPUUtilization'
    ScaleInCooldown: 60
    ScaleOutCooldown: 60
    TargetValue: 80

TrackingsCustom: &trackingcustom
  <<: *tracking
  Type: Custom
  TargetTrackingScalingPolicyConfiguration:
    CustomizedMetricSpecification:
      Dimensions: []
      Namespace: 'AWS/ECS'

StepDOWN: &stepdown
  <<: *step
  StepScalingPolicyConfiguration:
    StepAdjustments:
      - 0:
          MetricIntervalLowerBound: -10
          MetricIntervalUpperBound: 0
          ScalingAdjustment: -1
      - 1:
          MetricIntervalLowerBound: -20
          MetricIntervalUpperBound: -10
          ScalingAdjustment: -2
      - 2:
          MetricIntervalUpperBound: -20
          ScalingAdjustment: -2

StepUP: &stepup
  <<: *step
  StepScalingPolicyConfiguration:
    StepAdjustments:
      - 0:
          MetricIntervalLowerBound: 0
          MetricIntervalUpperBound: 10
          ScalingAdjustment: 1
      - 1:
          MetricIntervalLowerBound: 10
          MetricIntervalUpperBound: 20
          ScalingAdjustment: 2
      - 2:
          MetricIntervalLowerBound: 20
          ScalingAdjustment: 2


global:
  ApplicationAutoScalingScalingPolicy:
    - Cpu:
        <<: *trackingcpu
    - Custom:
        <<: *trackingcustom
    - Down:
        <<: *stepdown
    - Up:
        <<: *stepup
