IBoxLoader: !include
  - crm/certificate-global.yml
  - distribution.yml

global:
  Parameter:
    - CloudFrontLogging:
        Description: 'Empty for mapped value'
        AllowedValues: ['', 'yes', 'no']
    - CloudFrontWebACLId:
        Description: 'CloudFront WebACLId - empty for default based on env/role'
    - CloudFrontMinimumProtocolVersion:
        Description: 'The minimum SSL/TLS protocol and ciphers that CloudFront can use to communicate with viewers'
  Condition:
    - CloudFrontAcmCertificate:
        get_condition('', 'equals', 'yes', 'CloudFrontAcmCertificate')
    - CloudFrontLogging:
        get_condition('', 'equals', 'yes', 'CloudFrontLogging')
    - CloudFrontWebACLId:
        get_condition('', 'not_equals', 'none', 'CloudFrontWebACLId')
  Output:
    - CloudFrontWebACLId:
        Value: get_endvalue('CloudFrontWebACLId')
    - CloudFrontMinimumProtocolVersion:
        Value: get_resvalue('CloudFrontDistribution', 'DistributionConfig.ViewerCertificate.MinimumProtocolVersion')
  CloudFrontDistribution:
    - Base: {}
  CloudFrontAcmCertificate: 'yes'
  CloudFrontHttpVersion: 'http2'
  CloudFrontLogging: 'no'
  CloudFrontMinimumProtocolVersion: TLSv1
  CloudFrontWebACLId: none
