AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  BaseRegion:
    Fn::Equals:
      - eu-west-1
      - Ref: AWS::Region
  CloudFrontAcmCertificate:
    Fn::Not:
      - Fn::Equals:
          - true
          - None
  CloudFrontAliasExtra1:
    Fn::Or:
      - Fn::And:
          - Condition: CloudFrontAliasExtra1Override
          - Fn::Not:
              - Fn::Equals:
                  - Ref: CloudFrontAliasExtra1
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: CloudFrontAliasExtra1Override
          - Fn::Not:
              - Fn::Equals:
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - CloudFrontAliasExtra1
                  - None
  CloudFrontAliasExtra1Override:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontAliasExtra1
          - ''
  CloudFrontAliasExtra2:
    Fn::Or:
      - Fn::And:
          - Condition: CloudFrontAliasExtra2Override
          - Fn::Not:
              - Fn::Equals:
                  - Ref: CloudFrontAliasExtra2
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: CloudFrontAliasExtra2Override
          - Fn::Not:
              - Fn::Equals:
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - CloudFrontAliasExtra2
                  - None
  CloudFrontAliasExtra2Override:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontAliasExtra2
          - ''
  CloudFrontLogging:
    Fn::Or:
      - Fn::And:
          - Condition: CloudFrontLoggingOverride
          - Fn::Not:
              - Fn::Equals:
                  - Ref: CloudFrontLogging
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: CloudFrontLoggingOverride
          - Fn::Not:
              - Fn::Equals:
                  - None
                  - None
  CloudFrontLoggingOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontLogging
          - ''
  CloudFrontMinimumProtocolVersionOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontMinimumProtocolVersion
          - ''
  CloudFrontOriginsApiPortalCustomOriginConfigHTTPSPortOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsApiPortalCustomOriginConfigHTTPSPort
          - ''
  CloudFrontOriginsApiPortalDomainNameOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsApiPortalDomainName
          - ''
  CloudFrontOriginsClientPortalCustomOriginConfigHTTPSPortOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsClientPortalCustomOriginConfigHTTPSPort
          - ''
  CloudFrontOriginsClientPortalDomainNameOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsClientPortalDomainName
          - ''
  CloudFrontOriginsPortalStaticCustomOriginConfigHTTPSPortOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsPortalStaticCustomOriginConfigHTTPSPort
          - ''
  CloudFrontOriginsPortalStaticDomainNameOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontOriginsPortalStaticDomainName
          - ''
  CloudFrontWebACLId:
    Fn::Or:
      - Fn::And:
          - Condition: CloudFrontWebACLIdOverride
          - Fn::Not:
              - Fn::Equals:
                  - Ref: CloudFrontWebACLId
                  - None
      - Fn::And:
          - Fn::Not:
              - Condition: CloudFrontWebACLIdOverride
          - Fn::Not:
              - Fn::Equals:
                  - None
                  - None
  CloudFrontWebACLIdOverride:
    Fn::Not:
      - Fn::Equals:
          - Ref: CloudFrontWebACLId
          - ''
Description: portal-aman (Generated by awsibox 0.2.20) [clf]
Mappings:
  dev:
    eu-central-1:
      CloudFrontAliasExtra1: portal.dev.aman.arda
      CloudFrontAliasExtra2: None
    eu-west-1:
      CloudFrontAliasExtra1: portal.dev.aman.arda
      CloudFrontAliasExtra2: None
    us-east-1:
      CloudFrontAliasExtra1: portal.dev.aman.arda
      CloudFrontAliasExtra2: None
  prd:
    eu-central-1:
      CloudFrontAliasExtra1: portal.aman.arda
      CloudFrontAliasExtra2: valar-portal.aman.arda
    eu-west-1:
      CloudFrontAliasExtra1: portal.aman.arda
      CloudFrontAliasExtra2: valar-portal.aman.arda
    us-east-1:
      CloudFrontAliasExtra1: portal.aman.arda
      CloudFrontAliasExtra2: valar-portal.aman.arda
  stg:
    eu-central-1:
      CloudFrontAliasExtra1: portal.stg.aman.arda
      CloudFrontAliasExtra2: None
    eu-west-1:
      CloudFrontAliasExtra1: portal.stg.aman.arda
      CloudFrontAliasExtra2: None
    us-east-1:
      CloudFrontAliasExtra1: portal.stg.aman.arda
      CloudFrontAliasExtra2: None
Outputs:
  BrandDomain:
    Value: aman.arda
  CloudFrontMinimumProtocolVersion:
    Value:
      Fn::If:
        - CloudFrontAcmCertificate
        - Fn::If:
            - CloudFrontMinimumProtocolVersionOverride
            - Ref: CloudFrontMinimumProtocolVersion
            - TLSv1
        - Ref: AWS::NoValue
  CloudFrontWebACLId:
    Value:
      Fn::If:
        - CloudFrontWebACLIdOverride
        - Ref: CloudFrontWebACLId
        - None
  Env:
    Value:
      Ref: Env
  EnvRole:
    Value:
      Ref: EnvRole
  EnvStackVersion:
    Value:
      Ref: EnvStackVersion
  StackType:
    Value: clf
Parameters:
  CloudFrontAliasExtra1:
    Default: ''
    Description: Alias extra - empty for default based on env/role
    Type: String
  CloudFrontAliasExtra2:
    Default: ''
    Description: Alias extra - empty for default based on env/role
    Type: String
  CloudFrontLogging:
    Default: ''
    Description: CloudFront Logging - None to disable - empty for default based on
      env/role
    Type: String
  CloudFrontMinimumProtocolVersion:
    Default: ''
    Description: The minimum SSL/TLS protocol and ciphers that CloudFront can use
      to communicate with viewers
    Type: String
  CloudFrontOriginsApiPortalCustomOriginConfigHTTPSPort:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontOriginsApiPortalDomainName:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontOriginsClientPortalCustomOriginConfigHTTPSPort:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontOriginsClientPortalDomainName:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontOriginsPortalStaticCustomOriginConfigHTTPSPort:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontOriginsPortalStaticDomainName:
    Default: ''
    Description: empty for mapped value
    Type: String
  CloudFrontWebACLId:
    Default: ''
    Description: CloudFront WebACLId - empty for default based on env/role
    Type: String
  Env:
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
    Description: Environment
    Type: String
  EnvRole:
    AllowedPattern: ^[a-zA-Z0-9-_.]*$
    Default: ''
    Description: Service Role
    Type: String
  EnvShort:
    AllowedValues:
      - dev
      - stg
      - prd
    Default: dev
    Description: Environment Short - NEVER CHANGE!
    Type: String
  EnvStackVersion:
    Default: '1'
    Description: Stack version, if changed with UpdateMode=Cfn triggers cfn-hup
    Type: String
Resources:
  CloudFrontDistribution:
    Properties:
      DistributionConfig:
        Aliases:
          - Fn::If:
              - CloudFrontAliasExtra1
              - Fn::If:
                  - CloudFrontAliasExtra1Override
                  - Ref: CloudFrontAliasExtra1
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - CloudFrontAliasExtra1
              - Ref: AWS::NoValue
          - Fn::If:
              - CloudFrontAliasExtra2
              - Fn::If:
                  - CloudFrontAliasExtra2Override
                  - Ref: CloudFrontAliasExtra2
                  - Fn::FindInMap:
                      - Ref: EnvShort
                      - Ref: AWS::Region
                      - CloudFrontAliasExtra2
              - Ref: AWS::NoValue
        CacheBehaviors:
          - Compress: 'true'
            DefaultTTL: 86400
            ForwardedValues:
              Headers: []
              QueryString: 'false'
            PathPattern: /robots.txt
            TargetOriginId: portal-static
            ViewerProtocolPolicy: redirect-to-https
          - AllowedMethods:
              - DELETE
              - GET
              - HEAD
              - OPTIONS
              - PATCH
              - POST
              - PUT
            Compress: 'true'
            DefaultTTL: 0
            ForwardedValues:
              Cookies:
                Forward: all
              Headers: []
              QueryString: 'true'
            PathPattern: /api/*
            TargetOriginId: api-portal
            ViewerProtocolPolicy: allow-all
        Comment:
          Fn::Sub: portal.aman.arda (${EnvShort})
        CustomErrorResponses: []
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          Compress: 'true'
          DefaultTTL: 0
          ForwardedValues:
            Cookies:
              Forward: all
            Headers:
              - Host
            QueryString: 'true'
          TargetOriginId: client-portal
          ViewerProtocolPolicy: allow-all
        Enabled: 'true'
        HttpVersion: http2
        Logging:
          Fn::If:
            - CloudFrontLogging
            - Bucket:
                Fn::Sub: ${AWS::Region}-arda-aman-${EnvShort}-logs.s3.amazonaws.com
              Prefix:
                Fn::Sub: ${EnvRole}.${AWS::StackName}/
            - Ref: AWS::NoValue
        Origins:
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName:
              Fn::If:
                - CloudFrontOriginsClientPortalDomainNameOverride
                - Ref: CloudFrontOriginsClientPortalDomainName
                - Fn::Sub: client-portal.origin.${EnvShort}.aman.arda
            Id: client-portal
            OriginCustomHeaders:
              - HeaderName: X-SECRET-CFKEY
                HeaderValue: my-secret-key
            OriginPath: ''
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName:
              Fn::If:
                - CloudFrontOriginsApiPortalDomainNameOverride
                - Ref: CloudFrontOriginsApiPortalDomainName
                - Fn::Sub: api-portal.origin.${EnvShort}.aman.arda
            Id: api-portal
            OriginCustomHeaders:
              - HeaderName: X-SECRET-CFKEY
                HeaderValue: my-secret-key2
            OriginPath: ''
          - CustomOriginConfig:
              OriginProtocolPolicy: https-only
            DomainName:
              Fn::If:
                - CloudFrontOriginsPortalStaticDomainNameOverride
                - Ref: CloudFrontOriginsPortalStaticDomainName
                - Fn::Sub: ${AWS::Region}-arda-aman-${EnvShort}-portal-static.s3.amazonaws.com
            Id: portal-static
            OriginPath: ''
        PriceClass: PriceClass_100
        ViewerCertificate:
          AcmCertificateArn:
            Fn::If:
              - CloudFrontAcmCertificate
              - Fn::FindInMap:
                  - Ref: EnvShort
                  - Ref: AWS::Region
                  - GlobalCertificateArn
              - Ref: AWS::NoValue
          CloudFrontDefaultCertificate:
            Fn::If:
              - CloudFrontAcmCertificate
              - Ref: AWS::NoValue
              - 'True'
          MinimumProtocolVersion:
            Fn::If:
              - CloudFrontAcmCertificate
              - Fn::If:
                  - CloudFrontMinimumProtocolVersionOverride
                  - Ref: CloudFrontMinimumProtocolVersion
                  - TLSv1
              - Ref: AWS::NoValue
          SslSupportMethod:
            Fn::If:
              - CloudFrontAcmCertificate
              - sni-only
              - Ref: AWS::NoValue
        WebACLId:
          Fn::If:
            - CloudFrontWebACLId
            - Fn::If:
                - CloudFrontWebACLIdOverride
                - Ref: CloudFrontWebACLId
                - None
            - Ref: AWS::NoValue
    Type: AWS::CloudFront::Distribution

