AWSTemplateFormatVersion: '2010-09-09'
Conditions:
  BaseRegion:
    Fn::Equals:
      - eu-west-1
      - Ref: AWS::Region
  BucketElasticSearch:
    Fn::Not:
      - Fn::Equals:
          - true
          - None
  BucketElasticSearchAccountsReaddev:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchAccountsReadprd:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchAccountsReadstg:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchAccountsWritedev:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchAccountsWriteprd:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchAccountsWritestg:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchCors:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchPolicyRead:
    Fn::Or:
      - Fn::Equals:
          - '1'
          - '0'
      - Fn::Equals:
          - '1'
          - '0'
      - Condition: BucketElasticSearchAccountsReaddev
      - Condition: BucketElasticSearchAccountsReadstg
      - Condition: BucketElasticSearchAccountsReadprd
  BucketElasticSearchPolicyStatementReplicaPrincipal:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
  BucketElasticSearchPolicyWrite:
    Fn::Or:
      - Fn::Equals:
          - '1'
          - '0'
      - Fn::Equals:
          - '1'
          - '0'
      - Condition: BucketElasticSearchAccountsWritedev
      - Condition: BucketElasticSearchAccountsWritestg
      - Condition: BucketElasticSearchAccountsWriteprd
  BucketElasticSearchReplica:
    Fn::And:
      - Condition: BucketElasticSearch
      - Fn::Not:
          - Fn::Equals:
              - None
              - None
  BucketElasticSearchVersioning:
    Fn::Not:
      - Fn::Equals:
          - None
          - None
Description: res-s3-01 (Generated by awsibox 0.2.20) [res]
Outputs:
  BrandDomain:
    Value: aman.arda
  BucketElasticSearch:
    Value:
      Fn::If:
        - BucketElasticSearch
        - Ref: BucketElasticSearch
        - Fn::Sub: ${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
  Env:
    Value:
      Ref: Env
  EnvRole:
    Value:
      Ref: EnvRole
  EnvStackVersion:
    Value:
      Ref: EnvStackVersion
  StackType:
    Value: res
Parameters:
  Env:
    AllowedValues:
      - dev
      - stg
      - prod
    Default: dev
    Description: Environment
    Type: String
  EnvRole:
    AllowedPattern: ^[a-zA-Z0-9-_.]*$
    Default: ''
    Description: Service Role
    Type: String
  EnvShort:
    AllowedValues:
      - dev
      - stg
      - prd
    Default: dev
    Description: Environment Short - NEVER CHANGE!
    Type: String
  EnvStackVersion:
    Default: '1'
    Description: Stack version, if changed with UpdateMode=Cfn triggers cfn-hup
    Type: String
Resources:
  BucketElasticSearch:
    Condition: BucketElasticSearch
    Properties:
      BucketName:
        Fn::Sub: ${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
      CorsConfiguration:
        Fn::If:
          - BucketElasticSearchCors
          - CorsRules:
              - AllowedHeaders:
                  - Authorization
                AllowedMethods:
                  - GET
                AllowedOrigins:
                  - '*'
                MaxAge: 3000
          - Ref: AWS::NoValue
      VersioningConfiguration:
        Fn::If:
          - BucketElasticSearchVersioning
          - Status: None
          - Ref: AWS::NoValue
    Type: AWS::S3::Bucket
  BucketPolicyElasticSearch:
    Condition: BucketElasticSearch
    Properties:
      Bucket:
        Fn::Sub: ${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetBucketLocation
            Effect: Allow
            Principal:
              AWS:
                Fn::Sub: arn:aws:iam::${AWS::AccountId}:root
            Resource:
              Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
            Sid: Base
          - Fn::If:
              - BucketElasticSearchPolicyStatementReplicaPrincipal
              - Action:
                  - s3:ReplicateObject
                  - s3:ReplicateDelete
                  - s3:ObjectOwnerOverrideToBucketOwner
                Effect: Allow
                Principal:
                  AWS:
                    - Fn::Sub:
                        - arn:aws:iam::${BucketElasticSearchPolicyStatementReplicaPrincipal}:root
                        - BucketElasticSearchPolicyStatementReplicaPrincipal: None
                Resource: []
                Sid: AllowReplica
              - Ref: AWS::NoValue
          - Fn::If:
              - BucketElasticSearchPolicyRead
              - Action:
                  - s3:ListBucket
                  - s3:GetBucketLocation
                  - s3:ListBucketMultipartUploads
                  - s3:ListBucketVersions
                Effect: Allow
                Principal:
                  AWS:
                    - Fn::If:
                        - BucketElasticSearchAccountsReaddev
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReaddev}:root
                            - BucketElasticSearchAccountsReaddev: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsReadstg
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReadstg}:root
                            - BucketElasticSearchAccountsReadstg: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsReadprd
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReadprd}:root
                            - BucketElasticSearchAccountsReadprd: None
                        - Ref: AWS::NoValue
                Resource:
                  - Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
                Sid: AllowListBucket
              - Ref: AWS::NoValue
          - Fn::If:
              - BucketElasticSearchPolicyRead
              - Action:
                  - s3:GetObject
                  - s3:ListMultipartUploadParts
                Effect: Allow
                Principal:
                  AWS:
                    - Fn::If:
                        - BucketElasticSearchAccountsReaddev
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReaddev}:root
                            - BucketElasticSearchAccountsReaddev: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsReadstg
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReadstg}:root
                            - BucketElasticSearchAccountsReadstg: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsReadprd
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsReadprd}:root
                            - BucketElasticSearchAccountsReadprd: None
                        - Ref: AWS::NoValue
                Resource:
                  - Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch/*
                Sid: AllowGetObject
              - Ref: AWS::NoValue
          - Fn::If:
              - BucketElasticSearchPolicyWrite
              - Action:
                  - s3:Put*
                Effect: Allow
                Principal:
                  AWS:
                    - Fn::If:
                        - BucketElasticSearchAccountsWritedev
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsWritedev}:root
                            - BucketElasticSearchAccountsWritedev: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsWritestg
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsWritestg}:root
                            - BucketElasticSearchAccountsWritestg: None
                        - Ref: AWS::NoValue
                    - Fn::If:
                        - BucketElasticSearchAccountsWriteprd
                        - Fn::Sub:
                            - arn:aws:iam::${BucketElasticSearchAccountsWriteprd}:root
                            - BucketElasticSearchAccountsWriteprd: None
                        - Ref: AWS::NoValue
                Resource:
                  - Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch/*
                Sid: AllowPut
              - Ref: AWS::NoValue
        Version: '2012-10-17'
    Type: AWS::S3::BucketPolicy
  IAMPolicyReplicaBucketElasticSearch:
    Condition: BucketElasticSearchReplica
    Properties:
      PolicyDocument:
        Statement:
          - Action:
              - s3:GetReplicationConfiguration
              - s3:ListBucket
            Effect: Allow
            Resource:
              - Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch
          - Action:
              - s3:GetObjectVersion
              - s3:GetObjectVersionAcl
              - s3:GetObjectVersionTagging
            Effect: Allow
            Resource:
              - Fn::Sub: arn:aws:s3:::${AWS::Region}-arda-aman-${EnvShort}-elasticsearch/*
          - Action:
              - s3:ReplicateObject
              - s3:ReplicateDelete
              - s3:ReplicateTags
              - s3:ObjectOwnerOverrideToBucketOwner
            Effect: Allow
            Resource: []
        Version: '2012-10-17'
      PolicyName: IAMPolicyReplicaBucketElasticSearch
      Roles:
        - Ref: RoleBucketElasticSearchReplica
    Type: AWS::IAM::Policy
  RoleBucketElasticSearchReplica:
    Condition: BucketElasticSearchReplica
    Properties:
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - s3.amazonaws.com
        Version: '2012-10-17'
      Path: /
    Type: AWS::IAM::Role

